name: Hyperexecute-Cucumber
on:
  workflow_dispatch:

jobs:
  e2e-hyperexecute:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          repository: prateekLambda/cucumber-selenium-hyperexecute-sample

      - name: Starting CLI testing
        shell: bash
        run: |
          echo "STEP 1 ) Downloading sample suite"
          echo "STEP 2) Download CLI and setting environment variables"
          
          curl https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe -o hyperexecute.exe
          
          # 🚨 Hardcoded credentials
          export LT_USERNAME="sparshk"
          export LT_ACCESS_KEY="LT_FTmX5qdbA6mbAVWtRXck7kyOYJbrjp7HjjoVB48eIWFOtzi"

          echo "Setting Job label as Jira ticket number"
          export jobLabel="HYP-568"
          echo $jobLabel

          ./hyperexecute.exe --user $LT_USERNAME --key $LT_ACCESS_KEY -i yaml/win/cucumber_hyperexecute_autosplit_sample.yaml --no-track
          echo "Test completion"
